- CodeStarterCamp_Week3/main.swift
안녕하세요 글렌 ㅎㅎ @Journey36 
STEP1 보냅니당
- Person과 CoffeeShop이 나중에 상속하여 사용될 확장성을 생각은 해봤으나 필요로 프로젝트에서 사용될지는 의문이라서 struct인 구조체로 구현하였습니다.
- orderDrink메서드 구현시 price매개변수를 받을까 고민했지만 enum 을 Coffee타입으로 price를 연산으로 퍼티로 구현하면 가독성을 줄 일 수 있다고 판단하여 price에대한건 따로 받지 않았습니다.
- totalSales인 매출액은 외부로 공개할 필요는 없을것같아 private으로 설정하였습니다.
> Week3 [STEP 1] 쿼카

- CodeStarterCamp_Week3/CoffeeShop/CoffeeShop.swift
- CodeStarterCamp_Week3/CoffeeShop/Person.swift
- CodeStarterCamp_Week3/main.swift
안녕하세요 네프! @Neph3779
Step2 PR 입니다!
- struct와 class의 사용
- Person을 struct로 진행할 경우엔, 값을 복사하여 사용하기 때문에,
CoffeShop에서 Person의 buy 메서드를 호출하더라도 Person 원본의 money 속성 값은 변하지 않음.
- 따라서 원본이 공유될 필요가 있기 때문에(참조 될 필요가 있기 때문에), **Person**의 경우 참조 타입인 **class**를 사용하였습니다.
- **CoffeShop**의 경우에는 원본이 공유될 필요가 없기 때문에(참조 될 필요가 없기 때문에) 값 타입인 **struct**로 진행했습니다.
- 드디어 상속외에 뭔가 좀 유의미한 차이를 알게 된 것 같습니다! 하지만 여전히 뭔가 확실하게 딱 구분지어서 사용할 정도의 단계는 아닌 것 같습니다😭
- 혹시 네프가 봤을 때 네프였다면 해당 미션에서 이러한 이유로 이걸 사용했을 것 같다 정도의 의견을 여쭤봐도 될까요? 궁금합니닷
감사합니다!!
> Week3 [Step2] 마이노

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/Type.swift
- CodeStarterCamp_Week3/main.swift
@Neph3779 안녕하세요 네프!
wee3/step1PR 작성합니다.
이번주에 공부한 pattern 을 사용해보고싶었는데, enum이 나오길래 한번 사용해봤습니다.
그리고 다음 스텝의 내용을 확인하지 않고, Step1의 조건에 대해서만 고민하여 작성하다보니 step2에서 코드가 많이 바뀔수도 있겠지만.
우선 현재까지의 내용을 기반으로 PR작성합니다.
감사합니다!
> Week3 [STEP 1] JM.Y

- CodeStarterCamp_Week3/Step1.swift
- CodeStarterCamp_Week3/Step2.swift
- CodeStarterCamp_Week3/main.swift
@Ldoy 안녕하세요! 타코캣님! week3도 잘 부탁드립니다. 
---
commit 한 것 중에 Feat: yagombucks property initializer and Make some code for test은 제 코드가 잘 짜여진 코드인지 궁금하여 여러가지 테스트를 해본 코드입니다.
1.  **메뉴판(커피 종류, 가격)을 가질 수 있도록 해봅시다.**
라는 요구 조건에 대해 고민했습니다. 커피 종류마다 가격을 매칭시켜줘야 하니 딕셔너리를 사용했습니다. 딕셔너리 타입인 메뉴판의 key 값은 enum CoffeeType을 따르도록 했습니다. 이런 생각으로 코드를 짜봤는데 맞는 선택인지 모르겠습니다 ㅜㅜ
2. 물건을 구매할 수 있도록 메서드와 카페들이 공통적으로 할 수 있는 동작을 메서드가 구체적으로 어떤 동작을 해야하는지 몰라서 고민했습니다. 일단 제가 생각하는대로 구현해봤습니다.
3. 상속받는 객체(?)가 없어서 class 를 사용하지 않고 swift에서 좀 더 선호되는 struct를 사용했습니다. 이러한 판단이 맞는지 궁금합니다.
> Week3 [STEP 1] mmim

- CodeStarterCamp_Week3/main.swift
feature : CoffeeShop 구조체와 인스턴스 생성
feature : Person 구조체 생성
1. Person 구조체
-  사람의 속성으로 asset 정의했습니다.
- purchaseSomething 메서드 정의하여 price를 파라미터로 받고, 무엇인가를 구매하면 asset - price하여 remainder를 리턴하도록 했습니다.
2. CoffeeShop 구조체
- pickUpTable에 커피가 올라가있는지 없는지로 구분하기 위해 Bool 타입으로 정의했습니다.
- menu는 커피종류와 가격을 짝으로 나타내기 위해 dictionary를 이용하여 정의했습니다.
- 주문을 받는 order 메서드와 brewCoffee 메서드는 손님 이름과 커피종류를 받아 우선 프린트 하는걸로 구현했습니다.
- CoffeeShop 구조체 내에 Coffee 열거형을 정의하여 dictionary와 각종 메서드의 파라미터로 활용했습니다.
3. 각종 인스턴스 생성
- 바리스타인 misterLee와 손님인 missKim, 커피샵인 yagombucks 인스턴스를 생성했습니다.
menu에서 dictionary가 여러 짝이라 일렬로 쓰면 가독성이 떨어져서 한 줄씩 띄워서 썼는데 불필요한 공백을 줄이는게 좋을까요? 어떻게 생각하시는지 궁금합니다!
order와 brewCoffee 메서드의 customer 파라미터의 유형을 Person으로 주고, 45, 46번 줄의 yagombucks.order에서 customer: missKim으로 하면 print했을 때 missKim이 아니라 Person(asset: 3000)으로 찍혀서 …
> Week3 [STEP 1] marisol

- CodeStarterCamp_Week3/main.swift
안녕하세요 글렌! @Journey36 
STEP2 PR보냅니당 ㅎㅎ
최대한 메서드 기능을 분리하려고 시도했던것같습니다. 잘한지는 모르겠지만 잘 부탁드려요
추가로 어려웠던점과 특이한 오류가 발생하여 조언을 구하고 싶어요!
- `pickUpTable: [Coffee]?` 프로퍼티를 `pickUpTable()`메서드내에서 호출하려고 시도했으나 로직을 이해하기 어려운 nil값이 계속호출됩니다. 왜 nil이 나올까에대해서 궁금하여 외부에서 비슷한 형태로 코드를 만들어 출력해보았는데 `[프로젝트명.타입.case]` 이와같이 출력이 되는데 이부분과 연관이 있을까요 ?
- 위와같이 나오는 에러문구가 잘 이해가 되지않습니다. 기존에 struct는 멤버와이즈 이니셜라이저를 컴파일러가 제공하기때문에 지워도 문제없을거라고 생각을 했으나 `init()`을 지우니 위와같은 에러가 나옵니다..`private totalSales`을 만 `private`을 지정해주었는데 왜 레벨이 같지않다라는 문구가 나오는지 잘 모르겠습니다. 이유가 궁금하네요..^^
> Week3 [STEP 2] 쿼카

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
> WEEK3 [Step1] Minseong-yagom

- CodeStarterCamp_Week3/main.swift
@Journey36
안녕하세요 글렌
step3 PR 합니다.
고민한점
struct vs class
step1 에서 structure 로 클래스를 설정 했지만, takeOrder 메소드를 만들면서 mutating 으로 설정을 하니, Person structure에서는 CoffeeShop 안에 프로퍼티를 변경할 수 없어서, class 로 변경하였습니다.
확인하는 것을 깜빡해 main으로 PR 을 했네요.
수정하였습니다.
>  Week3 [STEP 2] cherrishRed 

- CodeStarterCamp_Week3/Step2.swift
@Ldoy 타코캣님! 
---
1. orderAndMakeCoffee를 3가지 func으로 나누어서 코딩했습니다. (order, calculateMoney, serveOnPickUpTable)
2. struct CoffeeShop의 property로 ```var customer: Person?```을 추가해주었습니다.
3.  struct CoffeeShop의 property인 pickUpTable에서 willSet을 이용하여 변화된 값이 감지되면 프린트 구문이 나오도록 추가했습니다.
---
궁금한 점
1. 이전에 step1에서는 Person을 struct로 지정해줬지만 class로 변경해주었습니다. 그 이유는 ```func calculateMoney```안에  ```customerOfCoffeeShop.money -= someCoffeePrice```에서 ```Left side of mutating operator isn't mutable: 'customerOfCoffeeShop' is a 'let' constant```라는 에러가 떠서입니다. Person의 프로퍼티인 ```var money: Int```에 새로운 값을 넣어줘서 생기는 에러인 것 같다고만 추측하고있고 이것이 class로 바뀌면서 왜 해결되는지 모르겠습니다 ㅜㅜ
> Week3 [STEP 2] mmim

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/coffeeShop.swift
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/person.swift
> Week3 [STEP 1] Taeangel

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/week3_step1.swift
@SoKoooool 
수지 안녕하세요! 3주차 step1 PR 보냅니다.
- Person
이름 - String으로 받기. pickUpTable에서 이름으로 주문을 구분할 예정
성별 - 둘 중 하나이기 때문에 enum
돈 -  0으로 초기화되게 하고 이니셜라이져에서 돈을 입력받는 것과 아닌 것 두 개.
이니셜라이져 - 구조체로 만들었기 때문에 memberwise 기능이 알아서 만들어줄 걸 알지만 처음이니까 연습하는 겸 일일이 적어주었습니다. money를 받지 않는 이니셜라이져는 필요하지만 세 개 다 받는 것은 안 써줘도 될 거 같아요. 
doOrder - 가격을 입력받고 가지고 있는 돈에서 빼주는 걸로 하나 만들었는데, CoffeeShop의 메소드에서 반환받은 총 가격을 받아서 처리하고 싶은데 방법을 조금 더 고민해봐야 할 거 같아서 우선 이렇게만 만들었습니다. 네이밍도 다시 하고 안에 코드도 조건문으로 다시 만들 예정입니다!
- CoffeeShop
커피 - 커피숍만 알고 있는 정보라고 생각해서 구조체 안에 Coffee 열거형을 넣었습니다. 
메뉴 - [커피종류: 가격] 이 되게 딕셔너리로. 정해진 값들이기 때문에 입력받지 않고 이니셜라이져에서 만들어준다.
sales - 총 매출액. 0으로 시작해서 주문받은 커피들의 가격을 더해줄 예정
pickUpTable - String 배열로 만들어서 Person.name을 순서대로 넣어주고 가져가면 앞에서부터 빼준다. 주문을 접수하면 만드는 메소드(굳이 필요 없어보여서)없이 바로 픽업테이블에 올려준다.
barista - 사람이 될 텐데, 입력에 따라 달라질테니 …
> Week3 [STEP1] venniek

- CodeStarterCamp_Week3/main.swift
> Week 3 [STEP 2] Minseong-yagom

- CodeStarterCamp_Week3/Type.swift
- CodeStarterCamp_Week3/main.swift
@Neph3779 안녕하세요 네프님!
Step2 진행하여 PR 발행합니다.
변경한 내용
1. `enum의 associated value`대신 `enum내에 computed property`를 사용해 보았습니다.
2. Barista라는 클래스를 만들고 Person을 상속받으면 어떨까 하여 Person을 'struct -> class'로 변경하였습니다.
궁금한 내용
구현 시 고민했던 몇가지 점들을 댓글로 남기겠습니다.
오늘도 감사합니다!
> Week3 [STEP2] JM.Y

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/Person/Person.swift
- CodeStarterCamp_Week3/Shop/CoffeeShop.swift
- CodeStarterCamp_Week3/Stuff/Coffee.swift
- CodeStarterCamp_Week3/main.swift
@joey-ful 
반갑습니다 Joey! 연말 잘 보내고 계신가요~ 조금 늦었지만 Week 3 미션 PR합니다💪
고민했던 점
* 메뉴판의 구현
카페마다 메뉴에 따른 가격이 다르기 때문에 이들을 CoffeeShop에서 매개변수로 Coffee를 전달받아 가격을 알려주는 함수를 새로 만들었습니다. 메뉴명도 각각 다르게 설정하고 싶은데 입력할 값이 너무 많아질 것 같네요
확실히 난이도가 점점 올라가는 것 같네요. 지금까지 학습한 내용을 복합적으로 사용해야 하는 것도 느껴지네요.
피드백 기다릴게요! 감사합니다~
> Week 3 [STEP 1] Grumpy

- CodeStarterCamp_Week3/classDirectory.swift
- CodeStarterCamp_Week3/main.swift
@Kioding 
미션에서 정의한것 이외에도 필요할꺼 같은 프로퍼티를 추가하였습니다.
> week3 step1 dnwhd0112

- CodeStarterCamp_Week3/coffeeShop.swift
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/person.swift
@jgkim1008 
Struct 를 사용한 이유는 
1 연관된 간단한 값의 집합을 캡슐화 하는 것만이 목적일 때 
2. 캡슐화된 값이 참조되는 것보다 복사되는 것이 합당할 때
3 구조체에 저장된 프로퍼티가 값 타입이며 참조되는 것보다 복사되는 것이 합당할 때
4 다른 타입으로부터 상속받거나 자신이 상속될 필요가 없을 때
다음중 한가지 이상 해당하면 struct 를 사용하는것을 권장한다 하여서 저는  1,4번 해당되고 초기화도 해줄필요가 없어서 struct를 사용했습니다. 
* 현재 CoffeShop 타입안에 중첩타입(Nested Types)으로 Coffee 타입을 구현해주셨는데요. 이렇게 진행한 이유가 있으실까요?? 이렇게 구현했을떄 장점과 단점은 무엇이 있을까요??
중첨타입은 장점은 코드를  좀더 깔끔하게 사용할 수 있는것이 장점이라 생각하고 사용하였는데  원시값으로 했을때 에러가 발생하여서 
저는 사용하지 않았습니다.
> Week3 [STEP 2] Taeangel

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/Coffee.swift
- CodeStarterCamp_Week3/CoffeeShop.swift
- CodeStarterCamp_Week3/main.swift
feat : order 함수에 계산 및 출력 기능 추가, brew 함수에 출력 기능 추가
1. order, brewCoffee 함수 내에서 turnover와 pickUpTable 등 자신의 프로퍼티를 수정해야해서, mutating으로 함수를 선언해줬습니다.
2. order 함수에서 커피를 주문했을때, customer의 asset이 커피 가격보다 값이 작으면 부족한 금액을 프린트하게 했습니다.
3. customer.asset > coffee.rawValue일때는 customer.asset과 coffeeShop.turnover의 값을 변경해주어야 하는데, 둘다 상수이기 때문에 새로운 변수 (각각 assetOfCustomer와 turnoverOfCoffeeShop) 를 생성해서 변경해주었습니다.
4. order 함수에서 고객이 커피 값을 지불했을 때 brewCoffee 함수를 호출했습니다. brewCoffee에서는 pickUpTable에 고객과 고객이 주문한 커피를 짝으로 저장하게 했습니다. 
열거형은 case별로 각각 다른 값을 가져야 하는 걸로 알고 있는데요, 이미 커피의 종류가 다 다른데, 원시값도 모두 다 달라야 하는 건가요?! 커피의 가격이 같은 경우 오류가 떴었어요.
감사합니다! @Tak95
> Week3 [STEP2] marisol

- CodeStarterCamp_Week3/Person/Person.swift
- CodeStarterCamp_Week3/Shop/CoffeeShop.swift
- CodeStarterCamp_Week3/Stuff/Coffee.swift
- CodeStarterCamp_Week3/main.swift
@joey-ful
안녕하세요~!🙋🏻‍♂️
3주차 2번째 미션 PR입니다 :)
고민했던 점
1. 본문 내용의 이해
> missKim 은 yagombucks 의 order(coffee: Coffee) 메서드를 호출해 커피를 주문합니다.
주문과 동시에 missKim의 돈은 커피의 가격만큼 줄어들고, yagombucks 의 매출액은 커피 가격만큼 증가합니다.
처음엔 이 부분이 잘 이해가 되지 않았습니다.. ```missKim```이 ```yagombucks```의 메서드를 호출한다면 ```missKim``` 인스턴스가 ```yagombucks```를 프로퍼티로 갖고 있어야 하는지, 또한 동시에 ```missKim```의 돈과 ```yagombucks```의 매출액을 조정하려면 어떻게 해야 하는지가 또 고민점이었습니다.
저는 조건문을 사용해서 커피의 구매 가능 여부를 ```Bool``` 타입으로 리턴하고, ```true```를 받으면 주문이 실행된 상황으로 간주하여 바로 ```yagombucks```의 ```order```메서드가 실행되도록 구현했습니다! 
2. 프로퍼티 옵저버
> 추출된 커피는 pickUpTable 에 올려집니다.
__pickUpTable에 커피가 올려지면__ 다음과 같은 문구가 출력됩니다.
```order``` 내부에서 바로 출력을 하면 쉽지만, 굳이 ```pickUpTable``` 에 커피를 올린다고 명시한 이유가 있을 것이라 생각했습니다.
그런 관점으로 접근하다 보니, __Property Observers__ 라는 것이 있더군요🤓
* willSet : 값이 저장되기 직전에 호출됩니다. 새로운 …
> Week3 [STEP 2] Grumpy

- CodeStarterCamp_Week3/classDirectory.swift
- CodeStarterCamp_Week3/main.swift
@Kioding 
기능을 조금 수정해서 올렸습니다.
type에 관해서는 라이브 세션이 끝나고 조사해볼게요! 아님 내일 ㅎㅎㅎ
> 2 dnwhd0112 week3 step2

- CodeStarterCamp_Week3/CoffeeShop.swift
- CodeStarterCamp_Week3/Person.swift
- CodeStarterCamp_Week3/main.swift
@Kioding 
키오 안녕하세요~~
요구사항에 맞춰 작성하기 위해 코드를 이것저것 수정했습니다.
Coffee가 원래는 CoffeeShop안에 있었는데
purchaseCoffee메소드 호출할때 
Coffee에 접근하기 불편해서 그냥 밖으로 뺐습니다..ㅎㅎ
프로퍼티 옵저버는 옛날에 멋모르고 공부할때는 
이걸 언제 쓰는거지.... 쓸데가 있을까...?? 라고 생각했었는데..ㅋㅋ..ㅠ
이번에 직접 써보니까 정말 좋네여!! 덕분에 코드도 간결해지고...!!
캠프 진행하면서 몰랐던 것도 배우고, 
알았던 것도 다시 한 번 공부 하면서 어떤식으로 활용하면 좋을지 더 생각하게 되고
계속 배우게 되는 것 같습니다! 
이번주가 끝이라는게 서운하네여ㅠ
> Week3 [STEP 2] hogang1223

- CodeStarterCamp_Week3/main.swift
@1Consumption 
올라프님 안녕하세요~
이번 3주차 스텝1은 타입과 인스턴스의 관계를 구현해보는 미션 이였습니다.
이번 미션에서 궁금했던 점은 Person구조체에 buyProduct와 CoffeeShop 구조체의 takeOrder가 나중엔 한 묶음으로 연결되어야 할텐데
둘을 이어주는 방법이 궁금했습니다.
항상 많은 조언 주셔서 감사합니다!
> Week3 [STEP 1] Kay Ahn

- CodeStarterCamp_Week3/main.swift
@TTOzzi 
또치님~! 안녕하세요😄 벌써 목요일이네요,,! 시간이 정말 빨리 지나갑니다!
step1 작성 완료해서 pr합니다! 
이번 과제의 경우 미션에서 주어진 오더보다, 뭔가 제가 결정해야 하는 것들이 많아서 고민이 됐었습니다.
그래서 질문 드릴건,
1. 저는 `coffeeShop` 구조체에 `barista`를 미리 변수로 생성해두었는데, 혹시 구조체에 미리 생성해두지 않고 이후에 새롭게 변수로 추가할 수 있는 방법은 없을까요? `How to add a var in structure`로 구글링 했었는데 딱히 유의미한 자료를 못 찾았습니다,,
> 2. `mutating func makeCoffee(person: String, coffee: Coffee) {` 에서 `person`을 `String`으로 정했는데, 처음에 작성할 때`person: Person`으로 받으니까
> ```swift
> yagombucks.makeCoffee(person: missKim, coffee: Coffee.americano) 
> // Person(name: "missKim", money: 100000)님 주문하신 americano 나왔습니다
> ```
> 이렇게 되더라구요ㅠ 그래서 일단 String으로 "misskim"을 받아서 `missKim님 주문하신 americano 나왔습니다`로 출력하게 만들었는데,
> 혹시 Person에서 이름만 뽑아내는 방법이 없을까요? _약간 Dict에서 menu[coffee]로 가격에 해당하는 값을 뽑는 것처럼요,,_
**😳 우왁! 해결했습니다! 프로퍼티 다시 공부하면서 …
> Week3 [STEP 1] lia388

- CodeStarterCamp_Week3/main.swift
@hcooch2ch3 
Bam 항상 감사드립니다.
이번에 미션을 최대한 요구사항대로 작성해 보았는데요.
pickUpTable을 가질 수 있도록 하라는 말이 뭔지 잘 이해가 안되서 일단 Array로 구현해봤는데 맞는지 궁금합니다.
> week3 [STEP1] Ohkyeongsik

- CodeStarterCamp_Week3/main.swift
@hcooch2ch3 
안녕하세요 밤! 스텝3 PR보냅니다.  
<br>
<br>
지난week2 에서 리뷰어 지정을 요청받았는데
저에게 권한이 없는 건지 못 찾은 건지 ... 계속 찾아봤는데 
저 톱니바퀴가 저에겐 보이지 않습니다.ㅠㅠ
> week3 [STEP1] moook

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/Step1.swift
- CodeStarterCamp_Week3/main.swift
열거형의 타입을 클래스 안에 저장 프로퍼티로 할다하여 활용하는 방법에 대해 고민이 해봤습니다.
감사합니다~ 좋은하루되세요~
@Monsteel
> Week3 [Step1] JeeeeSang

- CodeStarterCamp_Week3/main.swift
@Babywalnut 
안녕하세요 바비 ! 3주차 PR 드립니다
언제 class를 써야하고 언제 struct를 써야할지 아직 혼미하네요 ㅎㅎ
처음에는 struct로 타입을 구현했다가
step2에서 Person 타입과 Coffeshop 타입이 메서드 내에서
서로의 프로퍼티에 영향을 주게 구현해야하는 것 같아서 class로 변경하였습니다.
커피메뉴는 처음에 Coffee: Int 형태의 딕셔너리로 구현을 했다가
커피와 연결된 값이니 enum 내부에 프로퍼티로 넣어주면 좋을 것 같아서 수정했습니다.
> Week3 [STEP1] Ohtt

- CodeStarterCamp_Week3/main.swift
@YebinKim 
안녕하세요 비비!!
Week3-Step 1 과제 제출합니다.
이번 과제는 클래스, 인스턴스 ,구조체 등등 개념 이해하는 데 많은 시간을 쏟았습니다. (매우 헷갈렸어요..)
제가 코드를 작성하면서 가장 고민했던 점 두가지는
1. CoffeeShop 타입의 인스턴스로 yagombucks 을 생성해봅시다. 라는 조건의 과제가 있었는데,
```
var yagombucks: CoffeeShop = CoffeeShop(menu: [.coldBrew : 4500], sales: "$300", pickUpTable: 1, barista: misterLee)
```
저는 이렇게 구현을 해주었습니다.
menu: [.coldBrew : 4500] 이렇게 쓴 이유는 enum 으로 선언했던 Coffee의 coldBrew를 가져왔기 때문입니다. 
위에서 menu를 딕셔너리 타입으로 선언해준 이유는 커피 이름과 가격을 저장하도록 하기 위함이었는데요,
위의 코드에서 인스턴스 yagombucks에서 menu를 선언할 때 딕셔너리의 키값만 써주면 자동으로 value인 가격 4500이 출력되도록 하고 싶었는데, 저 부분은 타입에 맞추어 [String : Int] 의 값을 선언해주는 부분이었기 떄문에 아예 잘못된 생각이었을까요?
그 방법을 찾지 못해서 [.coldBrew : 4500]를 똑같이 써주게 돼었습니다.. 저 부분은 저렇게 써주는 것이 맞는건지 궁금합니다.ㅜㅜ
2. 두 번째 고민했던 점은, 
```
var yagombucks: CoffeeShop = CoffeeShop(menu: [.coldBrew : 4500], …
```
> Week3 [STEP1] yeeton

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
@uuu1101 
안녕하세요 태태
어느덧 week3의 과제를 제출하게되었네요.
```struct```를 사용하여 타입을 만들고 인스턴스를 생성했습니다.
```Coffee```를  열거형으로 만들고 가격을 원시값으로 두어 생성해보았습니다.
감사합니다.
> Week 3 [STEP 1] ryuyeon

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/step1.swift
@Journey36 
글렌님 안녕하세요!
Week3-step1 PR 드립니다!
타입 설계시 struct 로 할지 class 로 할지 부터 해서 속성의 타입까지 정해야 해서 고민이 많은 회차였습니다.
설계시, 고민 했던 내용을 정리 하여 보겠습니다.
struct 와 class 차이를 다시 찾아서 읽어보게 되는 좋은 계기 였습니다.
* stucrt
값타입 상속안됨 등..
* class 
참조타입 상속가능 등 ..
개인적으로 , step1을 구현하는 데는 딱히 구별할 필요가 없는것 같아서
일부로 익숙하지 않은 class 를 써보기로 하여 써봤습니다.
```swift
var yagombucks = CoffeeShop(totalSale: 0, menu: [[.americano:4500],[.tea: 2500],[.juice: 3000]], pickUpTable: 5)
```
yagombucks 는 총매출은 얼마이고, 메뉴와가격, 몇개의 pickuptable 갯수를 가지고 있는지 확인할수 있게 
설계 하고 싶어서 한눈에 볼수 있게 설계해 보았습니다. 
감사합니다.
> Week3 [STEP1] Makseong2

- CodeStarterCamp_Week3/main.swift
@1Consumption 
올라프님 안녕하세요~
이번 스텝 "인스턴스는 서로 소통한다" 를 구현했습니다.
이번 제 코드를 간략하게 설명드리면, 구조체를 이용해서 객체를 생성하고 객체가 어떤 행위를 할 수 있을때, 다음 동작을 실행하도록 했습니다.
저번에 말씀 해주신것 "구조안에서는 객체가 할 수 있는 기능을 구현하고 실제로 객체가 소통하는 과정은 그 밖에서 한다" 를 중점으로 구현했습니다.
이번에도 미흡한점 많이 조언 부탁 드립니다!
항상 감사합니다!
> Week3 [STEP2] Kay Ahn

- CodeStarterCamp_Week3/main.swift
@hcooch2ch3 
안녕하세요 🌰 
스텝 2 PR 보냅니다!
사용되지 않는 함수들을 삭제하였고,
구조체 내부 변수인 `sales` 값을 변경해주기위해 `mutating func` 를 사용했습니다.
`order 함수`에서 `money` 값을 변경하기위해 `Person`을 클래스로 변경했습니다.
`프로퍼티 감시자`를 이용하여 `pickUpTable` 값이 변경되면 
프린트 문이 나오도록 구현해보았습니다.
```
missKim님의 커피가 준비되었습니다. 픽업대에서 가져가주세요.
```
> week3 [STEP2] moook

- CodeStarterCamp_Week3/main.swift
@TTOzzi 
안녕하세요 또치님! 오랜만이에요😭
step2를 열심히 고민하다 step1의 구조체로 코드를 진행하기엔 어려움이 있어서, class도 공부할겸 바꿔봤습니다!
하나 바꾸니 저기가 오류나고, 또 하나 바꾸니 다른 오류가 나고ㅎㅎ 오래 걸렸습니다😅
이번 리뷰도 잘 부탁드립니다!😊
> Week3 [STEP 2] lia388

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/Step1.swift
- CodeStarterCamp_Week3/Step2.swift
- CodeStarterCamp_Week3/main.swift
@Monsteel 
init을 상속해줄 때 주의사항과 지켜야 하는 규칙에 대해 추가 공부하면서 과제를 해봤습니다.
감사합니다~ 좋은 하루 보내십쇼
> Week3 [Step2] JeeeeSang

- CodeStarterCamp_Week3/main.swift
@Babywalnut 안녕하세요 바비!!  
Step3 Step1 파일을 제출합니다...!  
이번에는 이번 스텝에서 원하는 기능을 최대한 구현해볼려고 노력해보았습니다..!  
또한 Step2에서 CoffeeShop이 사용되는 것을 보고 상속이 가능한 `class` 타입을 사용해 보았습니다.
메뉴판 같은 경우는 `dictionary`로 설정해 `커피 종류`의 `key`를 가지고 `가격`이라는 `value`를 가지도록 해보았습니다.  
`func order(coffee: Coffee)`는 출력을 할때에 옵셔널 값을 옵셔널 바인딩을 통해 추출했습니다.  
이번에도 피드백 잘 부탁드리겠습니다!
> WEEK3[STEP1]김동용

- CodeStarterCamp_Week3/main.swift
@hcooch2ch3 안녕하세요 밤님
이번엔 조금 오래 걸렸습니다. 클래스를 통해서 인스턴스를 생성 하는게 쉽지 않더라구요.
제가 미션을 진행하다가 막혔던 부분이 있는데 coffeeShop 클래스에서 클래스내에 만든 sales 프로퍼티를 클래스 내부의 함수에서 self.sales로 언급하여 +=를 통해 할당하니 숫자가 더해지지 않았습니다.
구글링을 통해 찾아본 결과로는 클래스 내부에서는 self를 통해 언급되면 오른쪽의 값이 새롭게 할당되는 것이 아니라 새로운 값이 할당 된다고 한 것 같아서 다른 변수를 생성해서 해결 하였습니다.
제가 한 방법이 맞는지 다른 방법은 뭐가 있는지 구글링을 통해 찾은 내용이 맞는지 궁급합니다!
항상 감사합니다.
> week3 [step2] 3_ohkyeongsik

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/structForCaffeeShop.swift
> Week3 [Step1] juho

- CodeStarterCamp_Week3/main.swift
@uuu1101 
안녕하세요 태태
week3 step2 제출합니다.
기존의 ```struct```였던 ```Person```과 ```CoffeeShop```를 ```class```를 이용하여 인스턴스끼리 소통하도록 만들어 봤습니다.
```missKim.orderCoffee(coffee: , coffeeShop: )```로 주문을 하면 ```money```와 ```coffee.rowValue```를 크기를 조건문으로 주문가능여부를 나누었습니다. ```CoffeeShop```에서 ```customer```를 추가하고 메서드들에 매개변수도 추가하여 픽업대에서 이름을 불러줄수있도록 작성하였습니다.
> week3 [step2] ryuyeon

- CodeStarterCamp_Week3/main.swift
@Journey36 글렌님 안녕하세요!  3주차 step2 작성해 봤습니다!
이번 스텝은 많이 어려웠던 것 같습니다...!  요구하는 결과 값들을 출력해 보았는데 어떤지 피드백 부탁드리겠습니다!
이 과제에 연산 프로퍼티(get, set)를 사용하여 매출액과 person.money를 계산이 가능한 코드가 있는것 같은데 
그렇게 코드 작성하는 것이 쉽지가 않았습니다. 
그리고 pickUpTable을 한번에 정의해서 사용하고 싶었는데 그 부분도 잘 이해가 가지않았습니다ㅜㅜ 
이번에는 class 상속을 사용해 Person의 부모 클래스로 coffeeShop을 사용 했지만 어디에 무엇이 맞는 상속인가
이 부분도 아직 부족한 것 같습니다. 지금 다시보니 상속을 잘못 한것 같기도하고,,, 하하;; 
글렌님 피드백 항상 감사합니다!!
> Week3[STEP2] Dason3027

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/step2 - order coffee.swift
- CodeStarterCamp_Week3/step2_ordercoffee.swift
@YebinKim 
안녕하세요 비비~ 
week3의 step2 과제 제출합니다!
1. week3의 step1 코드에서 잔액 확인하는 함수 hasAsset를 추가해주었습니다.
2. missKim이 커피를 주문하고, yagombucks에서 커피를 제조하고, 만약 missKim의 잔액이 커피 가격보다 부족하면 hasAsset이 false가 나오고, 잔액이 남으면 hasAsset이 true가 돼서 주문이 완료되도록 했습니다.
잘부탁드려요~~!!
> Week3 [STEP2] yeeton

- CodeStarterCamp_Week3/Coffee.swift
- CodeStarterCamp_Week3/CoffeeShop.swift
- CodeStarterCamp_Week3/main.swift
@uuu1101 안녕하세요 테테 투표는 하셨나요? :)
수정하면서 나눠서 commit 하는 연습을 해봤습니다!
어떤 기준으로 나눠야 하는지가 좀 헷갈리네요 ㅜㅜ 
검토 부탁드립니다!
> Week3 [Step2] namukim

- CodeStarterCamp_Week3/main.swift
@hrjy6278 
지스님 안녕하세요!
PR이 많이 늦어졌습니다,,,
Week3-step1 과제를 수행하였습니다!
이번 과제로 '사람' 클래스, '카페' 클래스 타입과 프로퍼티, 메소드 등을 정의해보고 
각 인스턴스끼리 값을 주고 받는 과정을 진행해 보았습니다!
1. 사람의 공통적인 속성을 프로퍼티, 동작을 메소드로 정의한 후에
직업(학생, 회사원, 군인, 개발자 등), 인종(황인, 흑인, 백인 등) 세부적인 그룹에 속한 사람들을 '상속'하여 만들기 위해
'클래스'로 정의해 보았습니다.
(1) 개인정보, 신체정보를 구조체로 선언한 이유
1. 각 그룹별로 연관된 프로퍼티를 모아서 하나의 데이터 타입으로 그룹화하여 표현하고 싶었습니다.
2. 위 그룹 타입은 상속할 필요가 없고, 상속받을 필요가 없기에 구조체로 타입을 지정하였습니다.
(2) 개인정보, 신체정보의 프로퍼티를 var(변수)로 선언한 이유
1. 사람의 특성 중 변경 가능한 모든 프로퍼티는 var로 선언하여 멤버의 값을 변경할 수 있도록 하였습니다.
(3) Person 클래스의 모든 프로퍼티를 생성자에 넣지 않은 이유
1. 사람의 필수정보들 위주로 생성자의 매개변수로 넣어보았습니다.
(4) 생성자가 2개 인 이유
1. 사람 중 직업, 학교, 직장이 없는 경우가 있을 수 있으므로,
이는 '옵셔널 타입'으로 구분하여 선언 후, 
위 프로퍼티가 필요한 경우와 필요하지 않은 경우로 구분하여 선언하였습니다.
(5) 생성자가 '옵셔널' 타입인 이유
1. '사람'의 특성에 맞지 않는 값이 생성자의 인자로 들어오는 경우,
nil 값을 반환하도록 하였습니다.
ex> …
> Week3 [Step1] SEO-YJ

- CodeStarterCamp_Week3/main.swift
안녕하세요, @ye-ha
이번 과제에서 다루는 것들이 낯선게 많은 만큼 신경쓸게 많았습니다.
- 우선 타입으로 구조체와 열거형을 사용했는데, 공식문서를 참고하여 클래스 대신 구조체를 사용했습니다. 문서에서 구조체는 추가 기능이 있는 만큼 복잡성이 높아져서 일반적인 상황에는 구조체 사용을 권장하고 있었습니다.
- name 프로퍼티는 한번 선언하면 바뀌지 않아서 상수, money 프로퍼티는 커피를 구매할때 바뀔 수 있어서 변수로 선언했습니다.
- `buyCoffee` 메소드 에서는 현재 가지고 있는 돈을 출력합니다.
- 매출은 판매량에 따라 변하므로 변수, 메뉴판은 고정되어 있으므로(물론 메뉴가 추가될 수도 있지만..!) 상수로 선언했습니다.
- menuList 프로퍼티에서는 열거형으로 선언한 Coffee 타입을 딕셔너리의 키값으로 가집니다.
- 과제 설명에서 
>pickUpTable 을 가질 수 있도록 해봅시다. (커피는 픽업테이블에 있을 수도 있고, 없을 수도 있습니다.)
라고 되어있어서 Bool과 Bool? 중 고민했는데, 커피가 준비되지 않아도 픽업테이블이 없는 건 아니므로 그냥 Bool 타입에 초기값을 false 로 선언했습니다.
- barista 프로퍼티는 초기값이 필요하지 않은 것 같아 Person? 타입으로 선언했습니다.
- barista 프로퍼티가 옵셔널 타입이어서 `getOrder`과 `makeCoffee` 함수에서는 옵셔널 바인딩을 이용했고, 바리스타의 name 프로퍼티를 출력하도록 우선 구현했습니다.
- Person 과 CoffeeShop 의 인스턴스 모두 커피를 구매, 판매하는 과정에서 …
> Week3 [STEP 1] inho

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/CoffeShop.swift
- CodeStarterCamp_Week3/Coffee.swift
- CodeStarterCamp_Week3/CoffeeShop.swift
- CodeStarterCamp_Week3/Person.swift
- CodeStarterCamp_Week3/main.swift
@jaemuYeo 
안녕하세요 잼킹! 😁
3주차 STEP1 PR요청 드립니다!
이번 주도 열심히 배우겠습니다!! 💪
이번 스텝에서 enum의 case들을 메뉴판에 추가하는 방법에 대해 고민을 많이 했습니다..
그러다 보니 커밋의 상태가 좀 복잡해진 것 같습니다 😭
> Week3 [STEP1] jeongmin(정민)

- CodeStarterCamp_Week3/main.swift
@leeari95 
```
var money: Int {
willSet {
print("주문 전 나의 돈 \(self.money)")
}
didSet {
print("주문 후 나의 돈 \(self.money)")
}
}
```
- 머니를 프로퍼티 감시자로 사용해봤습니다. 커피 주문을 해서 돈이 빠져나가면 돈이 나가기 전/후 얼마가 있는지 바로 알 수 있습니다.
```
mutating func buyCoffee(_ coffee: Coffee, at coffeeShop: CoffeeShop) {
guard let coffeePrice = coffeeShop.menu[coffee] else {
print("없는 메뉴")
return
}
if coffeePrice > money {
print("잔액이 \(coffeePrice - money)원만큼 부족합니다.")
} else {
print("\(coffeeShop.name)에서 \(coffee)를 주문합니다.")
self.money -= coffeePrice
coffeeShop.order(coffee, by: self.name)
}
}
```
- 커피메뉴(딕셔너리)에서 주문한 커피값을 가져오기 위해 옵셔널 바인딩 방법으로 guard let을 사용하였습니다. guard let은 값을 가져오지 못한경우에만 else로 처리합니다. 값을 가져올 경우 guard 문 밖에서 guard let에서 선언한 상수 coffeePrice를 사용할 수 있습니다.
- 저번주 스템에는 if let을 사용하였고 이번에는 guard let을 사용하여 옵셔널 바인딩 방법을 다시 복습해보았습니다. …
> Week3 [Step2] dooly

- CodeStarterCamp_Week3/main.swift
@July911 
- Step1
- 최초 CoffeeShop의 딕셔너리에 음료 종류와 가격을 넣었는데, 추후 Coffee 열거형에 커피종류가 들어가 변경했음.
- 메서드들을 구현했지만, 어디에 어떻게 쓰일지 고민을 하다가 대략적으로 구현했음.
> Week3 [STEP 1] beam2

- CodeStarterCamp_Week3/main.swift
안녕하세요.
@yim2627 
step1 pr 요청 드립니다.
struct와 class 관련한 사항을 몇번 봤다고 생각햇는데 실제로 만들어 볼려니 잘 구현이 안되네요.
애플 문서에 struct와 class중 선택 가이드가 있던데
- 연관된 간단한 값의 집합을 캡슐화 하는것만이 목적일때
- 캡슐화한 값을 참조하는 것보다 복사하는 것이 합당할때
- 구조체에 저장된 프로퍼티가 값 타입이며 참조하는 것보다 복사하는 것이 합당할때
- 다른 타입으로부터 상속받거나 자신을 상속할 필요가 없을때
중 하나 이상에 해당할때는 struct를 사용하는것을 권장하는데 아직까지는 와닿지는 않네요..
많은 코드를 구현해 보면서 부딛쳐 보면서 익혀봐야 할거 같습니다.
> Week3 [STEP 1] rimeorange

- CodeStarterCamp_Week3/main.swift
@July911
- Step2
- step1보다 간단하게 끝난거같네요.
- 초반에 너무 모호하게 시작해서 refactoring할게 많았던거같습니다
- 옵셔널 바인딩을 많이 사용해 보지 않아서 26번줄 확인한번 부탁드리겠습니다.
- 추후 말씀해주신 열거형 연산프로퍼티 공부해보고 적용해보도록 하겠습니다.!
> Week3 [STEP 2] beam2

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/CoffeeShop.swift
- CodeStarterCamp_Week3/Person.swift
- CodeStarterCamp_Week3/main.swift
@Jager-yoo 
좋은 저녁입니다! 저는 PR 보내고 저녁을 먹으러 가야겠어요! 
예거도 맛있는 저녁 드세요!!🤩
처음에는 ```CoffeeShop```의 ```menu```를 따로 ```커피종류```, ```커피값```로 프로퍼티 정의를 했어요. 
그랬더니 석연치 않음을 느꼈습니다... 각각 ```커피종류```-```커피값```으로 나중에 사용되어야 할텐데, 이렇게 만들면 이상하겠더라고요.
```커피종류```는 만든 열거형에서 가져온다 쳐도... ```커피값```은 어디서 가져와야하지? 
그때 키와 값을 동시에 보관해주는 Dictionary가 생각났습니다. 
이미 만든 열거형을 key값으로 Dictionary을 생성했어요.
혼자 해보다가 한참을 해매서 [애플 개발자 포럼](https://developer.apple.com/forums/thread/12315)에서 도움을 얻었습니다.
아직 배우진 않았지만, Step2의 내용을 살짝쿵 보니... 제목부터가 '인스턴스는 서로 소통한다' ...
왠지 ```상속``` 기능을 사용해야될 거 같아서 Class로 타입을 정의했습니다. 
인스턴스 생성을 main파일에 했는데, 맞는 방법인지는 모르겠어요.
플레이그라운드에서 코드를 구축하고, 과제 Xcode에 가져오는 방식으로 하고 있어서 소스파일을 만들고 하나씩 추가해보니...
딱히 main파일에는 코드를 넣을 게 없더라고요?? 그래도 main인데 비는 게 허전해보여서 인스턴스 생성 부분만 살짝쿵 넣어봤어요...()
Person 타입에 어떤 프로퍼티를 넣을까, 고민하다가 요즘 MBTI가 유행이잖아요! 그래서 한 번 …
> Week3 [Step 1] som

- CodeStarterCamp_Week3/main.swift
@oksunwoo 
* name, age, gender, hight, weight, money를 프로퍼티로 정의.
* 인사말, 자기소개, 한살증가, 돈계산 메서드 정의.
* 이니셜라이저는 name, age, gender, hight, weight값을 통해서 Person 생성. 하지만, 조건에 맞지 않는 값이 전달되면 nil반환. 
* cafeName, adress, sales, menu, pickUpTable, barista를 프로퍼티로 정의.
* 환영인사, 카페소개, 메뉴소개, 주문받기, 커피만들기, 커피upser하기 메서드 정의.
* 이니셜라이저는 cafeName, adress값을 통해서 CoffeShop 생성. 하지만, 조건에 맞지 않는 값이 전달되면 nil반환. 
1. 과거 학교에서 객체지향을 배울때 프로퍼티를 직접 값을 할당하고 얻는 방식은 좋지 않다고 배웠습니다. 즉, 프로퍼티를 private로 지정한 후 get, set메서드를 구현하여 해당 값을 추출하고 할당하는 방식이 올바르다고 배웠습니다. 이렇게 모든 프로퍼티를 메서드를 통해서 값을 추출하고 할당하는 형태로 구현해야 되는 건지 그렇게 하지 않아도 되는지 토니의 의견이 궁금합니다.
2. 주문받기, 커피만들기 함수에대해 질문이 있습니다. 코드 작성시 주문을 받게 되면 그 함수 내에서 커피만들기를 호출하는 것이 좋은 코드작성 인지 아니면 주문을 받고 해당 함수의 반환 값에 따라서 호출하는 것이 좋은 코드작성인지 궁금합니다.
> Week3 [Step1] Onestar

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/Coffee.swift
- CodeStarterCamp_Week3/CoffeeShop.swift
- CodeStarterCamp_Week3/Person.swift
- CodeStarterCamp_Week3/main.swift
@yaewonLee  
안녕하세요, 샬롯 🤗
3주차 1스텝 PR보냅니다..!!
즐거운 주말 되세용^^
> Week3 [STEP 1] Jessi

- CodeStarterCamp_Week3/main.swift
@oksunwoo 
지금까지 가장 고민 많이한 스텝이면서 동시에 정말 재밌게 수행한 스텝입니다! 
마치 퍼즐푸는거 같기도 하고, 게임하는거 같기도 하고 시간 정말 훅 지나갔어요!
> # class vs struct
이 부분 역시 고민했습니다만, class로 타입을 정의한 이유는 상속받을 수 있어서입니다!
+ Step에서는 나오진 않지만 Perosn이라는 이름에서부터 상속할 여지가 충분히 있다고 판단했습니다. CoffeeShop도 마찬가지구요!
+ 다만, 애플공식문서에는 struct를 기본적으로 상용하라고 하지만.. 상속을 위해 class를 포기하지 못했습니다!
> # class 내부에서 var or let
+ Person 클래스의 프로퍼티.
+ 사람의 이름과 나이는 변하지 않는다고 생각했습니다(물론 개명을 하거나 해가 바뀌면 나이가 바뀌지만 여기서는 고려하지 않을게요..!)
+ money는 사고 팔 때 당연히 변하는 값이므로 변수로 설정하였습니다.
+ CoffeeShop 클래스의 프로퍼티
+ 매출액을 의미하는 sales는 매달 변하므로 변수로 설정하였습니다.
+ coffeeMenu는 조금 고민했는데, 차후 메뉴가 추가될 수 있다고 생각되어 변수로 설정하였습니다.
+ barista 마찬가지로 고용하거나 해고당할 수 있어서 변수로 설정하였습니다.
+ pickUpTable은 프로퍼티 감시자로 정했기 때문에 변수로 설정하였습니다.
+ 어제 막 배운 didSet을 사용해보았습니다. 제가 느끼기엔 pickUpTable과 찰떡인것 같더라구요!
> # enum에서 원시값과 연관값
DM에서 보았듯이, Coffee의 종류들을 …
> Week3 [Step1] 윤세영

- CodeStarterCamp_Week3/main.swift
@oksunwoo 
***
***
1. pickUpTable : 과거엔 옵셔널을 사용하였으나 구매자의 이름도 포함되어야 해서 Dictionary를 사용하게 되었습니다.
2. 기타 다른 수정사항은 기능을 구현하기위해 수정되었습니다.
***
1. 현재 생성된 3개의 인스턴스는 전부 실패 가능한 인스턴스입니다. 이러한 경우에 실패를 했는지 안 했는지 모르기 때문에 옵셔널을 사용하여 해당 인스턴스를 사용하고 있는데요. 이렇게 사용하는게 좋은지 guard를 사용하여서 사용하는게 좋은지 어떤 사용이 더 좋은사용인가요??
> Week3 [Step2] Onestar

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
- step1.swift
@eunseo5355 
안녕하세요~ Week3 Step1 PR 요청드립니다.
`class` 타입과 `struct` 타입 중 어느 것을 사용할지 고민하다, 기존에 익숙한 `class` 타입을 사용했습니다 (상속이 필요할 경우를 대비해서)
`Person`과 `CoffeeShop`을 각각 정의하고 이들의 인스턴스를 생성할 때 초기값에 대한 정보가 없어
프로퍼티 중 변수에 초기값을 할당할 것인가 (`money: Int = 0`과 같이) 또는 `init`을 활용할 것인지 고민하다가
`Person`의 `money`와 `CoffeeShop`의 `sales`는 초기값을 `0`으로 할당하고,
`barista`는 만들어져있는 Person 인스턴스가 있는 지 알 수 없기에 이니셜라이저를 사용했습니다. (카페에는 바리스타가 꼭 있어야 한다고 생각해서 옵셔널로 작성하지 않았습니다.)
-> 합리적/타당하게 작성된 것이 맞는지 궁금합니다.
첨부의 코드와 같이 작성 시,
main 파일에서 `CoffeeShop`의 인스턴스 `yagombucks`를 아래와 같이 생성하니,
```swift
var yagombucks: CoffeeShop = CoffeeShop(barista: misterLee)
```
다음과 같은 오류가 발생했습니다.
```
Editor placeholder in source file
```
`menuBoard`와 `pickUpTable`에 값이 할당되어 있지 않기 때문에 발생하는 오류인 것 같은데 맞을까요?
그리고 이렇게 (오류가 발생하도록) 작성해도 문제의 지시사항에 부합하는지 궁금합니다.
감사합니다!
> Week3 [STEP3] summer

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/Week3Step1Coffee.swift
- CodeStarterCamp_Week3/Week3Step1CoffeeShop.swift
- CodeStarterCamp_Week3/Week3Step1Person.swift
- CodeStarterCamp_Week3/main.swift
안녕하세요 제인님! @siwonkim0
Week3 Step1 타입과 인스턴스의 관계 PR 드립니다!
이번 미션... 쉽게 생각했으나 고민거리만 한 가득인거 같습니다... 나름대로 열심히 했는데 잘 모르겠습니다...ㅠㅠ
백엔드 개발 배울 때 각 Router들을 모듈화해서 작업능률을 올렸던 것이 떠올라 class들과 열거형을 파일마다 저장하였습니다.
코드가 적을 때는 하나의 파일에 작성하는 것이 편할 수도 있지만 코드의 수가 늘어날 경우 파일이 무거워져 자칫 성능 저하로도 이어질 수 있기 때문에 모듈처럼 나눠보았습니다. (물론 코드가 긴 건 아닙니다... 그냥 그렇다는 것...)
다행히 프로젝트에 타겟이 맞춰져서 다른 파일에서 값을 가져올 때 `import` 하는 일이 없어서 귀찮음이 덜 했습니다.
`import Foundation`이 그 역할을 하는건가? 하는 생각도 들었습니다.
- Commit 하고나서야 Commit Convention이 일정하지 않은 것을 확인했습니다... 앞으로는 좀 더 주의 깊게 작성하겠습니다.
1. 구조체 VS 클래스
: Step2까지의 내용을 보니 카페에서 커피를 구매하고 픽업테이블에서 가져가게 되면 `missKim`은 카페를 떠날 것으로 생각하였습니다. 
그래서 카페를 떠난 `missKim`을 메모리에서 `Deinitialize` 하기 위해 `class` 타입으로 정의하였습니다. 
(Step2에서 구현해보고자 합니다.)
2. `CoffeeShop` 클래스 - `cafeMenu` 메소드에 메뉴와 가격 할당하기
: 아래쪽에 질문으로 남겼지만 요구사항의 메뉴판을 정의하는 부분이 조금 …
> Week3 [Step1] keyster

- CodeStarterCamp_Week3/main.swift
안녕하세요, @ye-ha 🙂 이번 PR도 잘부탁드립니다ㅎㅎ
새로운 과제를 구현하기 위해 지난 코드에서 바뀐부분이 꽤 많습니다!
**구조체에서 클래스 변경** 
- 지난 스텝에서는 모두 구조체를 이용했었는데, 이번에는 클래스로 전부 변경했습니다. 커피를 barista 가 추출해야 하므로 Barista 라는 타입을 새로 만들고 Person 타입을 상속한 뒤, 새로운 프로퍼티와 메소드를 추가하는 방식을 이용하기 위해 클래스를 사용했습니다.
**Person 클래스**
- 구조체에서 클래스로 변경되어서 `init()` 함수를 추가했습니다.
- `buyCoffee()`함수를 `buy(_ coffee, at coffeeShop)`함수로 변경하였습니다. 손님이 주문을 할 때, 메뉴 이름과 본인 이름을 말해야 하기 때문에(출력결과를 위해) 두 매개변수를 주고, 호출할 때 함수 이름과 argument label의 의미가 잘 전달되도록 했습니다.
**CoffeeShop 클래스**
- barista 변수에 옵셔널 Barista 타입, customer 변수에 옵셔널 Person 타입을 지정했습니다. ( 커피샵을 초기화할 때, 직원과 손님을 모를 수도 있어서)
- Person 클래스에서 Coffee 열거형에 접근하도록 하기 위해 CoffeeShop 안에서 꺼냈습니다.
- 기존의 order 함수에 Coffee 타입 매개변수를 추가하여 주문받은 메뉴를 알 수 있도록 했습니다.
- 주문을 받기 전에 옵셔널 바인딩을 통해 직원이 있는지, 손님이 있는지, 손님이 고른 메뉴의 가격이 메뉴판에 있는지 확인합니다.
- 주문을 받을때 손님의 잔액이 …
> Week3 [STEP 2] inho

- CodeStarterCamp_Week3/main.swift
@jaemuYeo 
바리스타가 여러명일지도 모른단 생각에 배열로 작성을 했습니다.
`var barista: [Person]?`
처음에는 이렇게 작성했으나 인스턴스를 생성할 때 
자동으로 배열을 초기화시켜주지않아 `.append`를 해도 오류가 계속 떴습니다.
`var barista:  [Person] = []`
미리 초기화를 하니 `.append`도 잘 동작했어요!
열거형에 원시값을 바로 넣어줘도 되지만,
개별로 관리하고 싶어서 CoffeeShop의 menu를 딕셔너리 형태로 만드는 것을 택했습니다!
또한 사람이 방문한 커피샵도 매개변수로 받아, 커피샵을 통해 가격을 가져오는 방법을 사용했어요
> Week 3 [STEP 1] Oh Sung Ah

- CodeStarterCamp_Week3/CoffeeShop.swift
- CodeStarterCamp_Week3/Person.swift
- CodeStarterCamp_Week3/main.swift
@llghdud921 
안녕하세요 제리~
CoffeeShop은 Class 타입으로 변경하였습니다. 변경한 이유는  구조체는 값타입이기에 값의 복사가 이루어져서. 변수를 할당하면 복사가 일어나고 복사된 값을 가져오는것이기에 원본 인스턴스에는 반영이되지 않아 class를 사용했습니다.
> Week3 [step2] duck

- CodeStarterCamp_Week3/main.swift
@yim2627 
안녕하세요 지성님!
Week3 Step2 Pr 보냅니다.
프로퍼티 감시자를 이용해서 커피 주문 완료를 구현해 보았습니다.
> Week3 [Step2] rimeorange

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/CoffeeShop.swift
- CodeStarterCamp_Week3/Person.swift
- CodeStarterCamp_Week3/main.swift
@jaemuYeo 
CoffeeShop의 order 메소드에 매개변수 (Person의 name)을 추가했습니다
Person 타입을 받아오기엔 불필요한 정보(money)가 있다고 판단되었 기에, name만을 String으로 받아오는 것으로 했습니다.
Person의 name과 주문한 coffee를 출력하기 위해서 Dictionary로 구성을 했는 데요.
기왕이면 n번째 주문도 출력하는 것도 좋지않을까~해서 Array(Dictionary)형태로 바꾸었습니다.
**_다만 초기화할 때 자동으로 0번이 들어가는 지, 주문을 받고 append하면 1번부터 들어가네요.. 이부분은 잘모르겠습니다_**
Coffee에서 case문으로 구성한 걸 한글로 출력하기 위해 원시값(String)을 추가했습니다.
그리고, willSet과 didSet을 연습하기 위해 Person의 money에 프로퍼티를 추가했습니다!!
> Week 3 [STEP 2] Oh Sung Ah

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/Coffee.swift
- CodeStarterCamp_Week3/CoffeeShop.swift
- CodeStarterCamp_Week3/Person.swift
- CodeStarterCamp_Week3/main.swift
@yaewonLee 
안녕하세요 샬롯,
연휴 잘 보냈나요?
제가 드디어 커피를 사먹을 수 있게 되었습니다 🎉
--- 
- CoffeeShop을 구조체로 작성을 하다보니 Person에서 결제를 한 금액을 Shop으로 받아오는 부분에 오류가 났습니다.
(CoffeeShop의 총매출 부분의 금액이 바뀌지 않음)
- Person의 오류
```swift
shop.order(coffee)
//Cannot use mutating member on immutable value: 'shop' is a 'let' constant
```
- CoffeeShop의 오류
```swift
sales += coffee.price
//Left side of mutating operator isn't mutable: 'self' is immutable
```
검색을 해보니,
- Swift에서 함수의 파라미터는 상수이므로 함수 내부에서 파라미터의 값을 변경할 수 없다.
inout 파라미터를 사용해 CoffeeShop에 inout을 붙였습니다.
```swift
mutating func buy(shop: inout CoffeeShop, coffee: Coffee) {
```
- inout을 이렇게 사용하도 괜찮은건가요?
- "잔액이 {커피가격}원만큼 부족합니다." 부족한 잔액이어야 하므로 커피가격이 아닌, 부족한 만큼의 금액으로 반영했습니다.
> Week3 [STEP 2] Jessi

- CodeStarterCamp_Week3/main.swift
@ye-ha 
- 더 세밀하게 생각도 해봤지만, 일단은 과제에 주어진 정도 내에서 생각해보려고 했습니다. 메뉴를 선택하고, 돈을 지불하고, 커피를 받는 순으로 생각해봤습니다.  
- 커피숍은 주문을 받고, 돈을 받고, 주문 받은 메뉴를 만들고, 픽업대에 올려놓는 순으로 생각했습니다.
- 사람은 개개인의 특성이 다르기 때문에 참조 타입인 클래스를 사용할 순 없다 판단하였습니다. 
- 커피숍도 마찬가지의 이유로 각 커피숍 별 바리스타와 현재 주문 상황, 매출액 등이 다 다를 수 있기 때문에 참조 타입을 사용하는것은 적절하지 않다 판단하였습니다.
- 처음에는 각 커피의 가격, 컵의 사이즈, 찬음료인지 차가운 음료인지, 등등의 연관 값을 넣어서 커피를 좀 더 세세하게 구분하고자 하였습니다.
- 그런데 제가 연관 값을 잘 활용하지 못한 상태였기에 이를 억지로 활용하다 보니 오히려 코드를 짜는데 더 큰 어려움들이 많이 생겼습니다.
- 예를 들어 각 연관 값을 상수로 빼내어 이를 활용하는 방법이라던가.. 이런 부분들의 방법 자체는 알았지만 이 코드에 녹이는 것까지는 하지 못했습니다.
- 위와 같은 이유로 열심히 만들어 두었던 커피 열거형을 모두 지우고 간단하게 원시 값과 커피 가격을 호출해주는 함수를 만들어서 사용하는 방법을 선택했습니다.
- 과제에서 제시한 부분들은 나름대로 풀었다고 생각하지만, 이렇게 타협하는 게 괜찮은 건지 조금 의문이 듭니다. 저 연관 값을 활용하는 게 맞는 판단이었을까요?
> Week3 [STEP 1] wonbi

- CodeStarterCamp_Week3/main.swift
@Allie-e 
앨리 안녕하세요! WEEK3 [STEP1] 미션을 완료했습니다 :)
이번 미션을 진행하면서 어려웠던 점 질문드립니다!
카페 메뉴를 열거형으로 정의하면서, `rawValue`로 가격을 넣어주려고 했는데 `rawValue`를 같게 선언하니 에러가 생겼습니다 ㅠㅠ
구글링 해보니까 원시값은 unique 해야하므로, 값이 같을 수 없다고 나오더라구요,, 그래서 해결할 방법을 찾다가, 외국 사이트에서 순환 열거형을  사용해 해결한 코드를 보고 제 코드에도 활용하게 되었습니다. 이렇게 원시값을 같게 설정해야할 경우에 순환열거형을 사용하는 것이 적절한지 , 그리고 순환 열거형은 어떤 경우에 활용되는지도 궁금합니다!
저는 카페 메뉴에 대한 프로퍼티를 `menu`와 `menuPrice`로 나누어 선언했는데, 미션 설명에서 `메뉴판(커피 종류, 가격)을 가질 수 있도록 해봅시다.` 라고 나와있어서, 메뉴판이라는 한 가지 인스턴스 안에 커피 종류와 가격을 모두 나타낼 수 있어야 하는지 고민하게 되었습니다... 혹시, 이렇게 한 가지 인스턴스 안에 타입이 다른 두 가지 값을 동시에 갖도록 하는 있는 방법이 있을까요??
```swift
let yagombucks: CoffeShop = CoffeShop(salse: 0, menu: " ", menuPrice: 0, pickupTable: true, barista: misterLee)
yagombucks.menu = "\(coffeMenu.카라멜마끼야또)"
yagombucks.menuPrice = coffeMenu.카라멜마끼야또.coffeePrice
```
위의 …
> WEEK3 [STEP1] dorii

- CodeStarterCamp_Week3/main.swift
@leeari95 
안녕하세요! week3 step1 PR 드립니다!!
week3을 공부하면서 몇가지 궁금한 점이 있어서 질문드립니다!!
먼저 미션에서 어려웠던 점이 카페의 메뉴판을 만드는 부분이였는데, 커피의 종류와 가격을 담을때 커피의 종류가 미션에서 제시한 Coffee 타입 열거형과 어떻게 엮어서 만들어보라는 의미인걸로 해석했는데요! 그래서 enum으로 만든 Coffe타입을 상속받아 사용하려고 시도했는데 enum 타입은 상속이 안된다고 해서 고민하다가 그냥 따로 struct로 적어주었어욤.. 근데 이게 올바른 답은 아닌것 같은데 더 좋은 방법이 있을까요? 힌트 부탁드립니다..🤣
그리고 Person과 CoffeeShop의 타입을 결정할 때 class를 사용하였는데요! 클래스와 구조체의 차이점을 고려했을 때 값 타입을 사용하면 수정되는 정보가 반영되지 않는다고 판단해 class로 작성하였습니다!!
이번 PR도 잘 부탁드립니다!!!😆
> WEEK3 [STEP1] Lily

- CodeStarterCamp_Week3/main.swift
@jaemuYeo 
잼킹 디엠으로 질문을 드리려다가, 한국말로 뭐라고 해야할지 모르겠어서 그냥 PR로 보냅니다!
사실 질문이라고 할 것도 어느 부분에서부터 질문을 해야할지 모르겠어요. 
구조체에 대한 개념을 잘 모르겠어서..., 이렇게 쓰는게 맞나? 라는 생각이 계속 듭니다.😨😢
미션에서 이렇게 하는걸 원하는건가? 하는 생각이 계속 들어서 하나씩 해보긴 하는데 이렇게 하는게 맞나요?? 
일단 궁금했던 건, class 를 선택해야 하는지 struct를 선택해야 하는지도 잘 모르겠어요. 기준? 이 있는지 궁금합니다. 
값의 타입을 갖느냐 참조 타입을 갖느냐로 구분하는 것 같은데 어떻게 ?? 구별하지 ?? 이런 생각입니다. 
두번째는 메서드로 주문을 받고 커피를 만들어낼 수 있는 동작을 만들라고 하셨는데. 정말 "말로만" 제조 중이라 과정이 따로 필요한건가? 하는 생각이 들었어요 
세 번째는 인스턴스 생성하는거 관련해서인데요. 인스턴스 초기화를 해줘야하는 것 같은데 init으로 초기화 하긴 했는데, 값을 일일히 지정해줘야하는건가?🤔 하는 의문이 생겼습니다. 
Week3 너무 어려워서 강의를 몇 번이나 돌려봤는데 아직도 이해가 잘 안되네요...😢
> Week3 [Step 01] OneE

- CodeStarterCamp_Week3/coffee.swift
- CodeStarterCamp_Week3/coffeeShop.swift
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/person.swift
@yim2627 week3 step2 입니다.
지성님, 궁금한게 있는데요!
enum 안에 있는 case 가지고 dictionary 활용하는 방법은 없나요?
greeting 함수에서 인사를 하고 나서 메뉴판 출력을 하려고
뭔가 dictionary를 활용 할 수 있지 않을까? 했는데 아무리 찾아봐도 잘 모르겠어요
그래서 결국 allCases와 for문을 활용했습니다.
> Week3 [STEP 2] suyeon

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/CoffeeShop.swift
- CodeStarterCamp_Week3/Person.swift
- CodeStarterCamp_Week3/main.swift
@ye-ha 
- 이전 스텝에선 메인에 코드를 전부 작성했는데, 위아래로 좀 길어지다보니 위아래로 오르락 내리락하는게 귀찮더라구요. 그래서 이번 스텝에서는 `Person`과  `CoffeeShop`으로 나눠서 양쪽에 띄워두고 코딩을 했습니다.
1. `.init`
- 일단 변수를 선언하는 부분에서 말씀해주셨던 대로 `.init`이 오히려 가독성이 떨어지는거 같더라구요. 그래서 `var misterLee = Person(name: "misterLee", money: 0)` 다음과 같이 수정하였습니다.  
2. `Queue`타입과 네이밍
- 저는 `Queue`라는 타입이 있는지 몰라서 이런 문제가 생긴거 같아요. 이름을 어떻게 해주면 좋을까 고민하다가 `orderList`로 바꿔주었습니다.
3. `orderList`의 옵셔널 언래핑
- 각 함수별로 언래핑하는 방식보다 미리 언래핑하는 방식을 활용하기위해, 언래핑을 하고, 그 값을 파라미터로 받는 함수들을 호출하는 방식으로 변경해보았습니다.
4. `pickUpTable`의 타입
- `pickUpTable`의 타입을 Bool 타입으로 바꾸고, 프로퍼티 감시자를 활용했습니다. 바리스타가 커피를 완성하면 `pickUpTable`의 값을 `true`로 바꾸고, 바꾸기 직전에 커피 제조가 완성되었다는 메시지를 출력한 후, 값이 바뀌면 자동으로 픽업하라는 메시지가 나오도록 활용했습니다.
5. 메소드 네이밍
- 일단 과제에서 제시한 메소드 명을 따르기 위해 `takeOrder`의 메소드를 `order`로 수정한 후, 과제에서 제시한 동작을 할 수 있도록 수정했습니다.
- …
> Week3 [STEP 2] wonbi

- CodeStarterCamp_Week3/main.swift
@leeari95 
안녕하세요😆 week3 step2를 진행하면서 궁금했던 몇가지 질문사항 드립니다!
1. 기존에는 Person과 CoffeeShop를 struct으로 작성했는데 이번에는 class로 변경하였습니다. 
struct으로 작성하던 중 mutating을 이용하여 문제없이 코드를 작성하였는데, 카페 수익금을 계산하는 부분에서 금액이 누적되지 않아 고민하다가 struct가 값 타입이라는 특성 때문에 그런가 해서 class로 변경하여 작성하였습니다! 
이 부분을 제가 옳게 판단한건지 궁금합니다..🥺
2. 기존 문제에서 제시되었던 ```order(_ coffee: Coffee)``` 대신 커피가 픽업테이블에 올려졌을 때 주문한 사람을 함께 출력하기 위해 person이라는 매개변수를 추가하여 ```order(_ coffee: Coffee, who person: String)``` 와 같이 작성하였습니다. 
제가 생각하기에 주문한 사람의 이름을 출력하려면 order함수를 호출할 때 누가 주문했는지를 전달해주어야 주문한 사람이 누군지를 CoffeeShop클래스에서 파악할 수 있을것 같더라고요.. 
근데 문제에서 제시한 조건과 맞지 않아서 다른 방법이 있는지 궁금해 질문드립니다!🤣
이번 PR도 잘 부탁드립니다!!😆
> WEEK3 [STEP2] Lily

- CodeStarterCamp_Week3/main.swift
@jaemuYeo 
잼킹 고민 끝에 저는 타협을 시도했습니다. 
일단 문제에서는 고객이 missKim 한명이니까, yagomBucks의 손님은 missKim만 받기로 했어요.
잼킹이 맥북을 닫기 전에 주셨던, pickUpTable의 값을 바꾸는 것은 성공했으나, 
```swift
if let customer = self.customer { } 
```
구문을 포함해서 넣으면, 뭔가 값이 입력되지 않는건지 (아마 제가 추가로 뭘 해야하는건데, 제가 못하는 거겠죠...)
아예 print() 자체가 실행되지 않더라구요. 
그래서 결론적으로 야곰벅스의 손님은 일단 김미영씨만 받기로 했답니다. 🤔 뭔가 더 고민하면 될 것 같긴 한데 일단..., 하나의 과제를 성공해서 PR을 보내요!
> Week3 [Step2] OneE

- CodeStarterCamp_Week3/main.swift
@July911 
이번주차가 저에겐 fear zone이였어요 😫 새로 알게된 개념들로 step을 진행하려니 처음엔 감이 안잡혀서 힘들었지만 그래도 쥐어짜서 해봤습니다 ..!
- 우선 타입을 정의할 때 class 보단 struct위주로 사용하려고 했습니다. swift언어에서 struct를 선호한다는 말도 생각났고 각 인스턴스의 값이 달라야 한다고 생각했습니다. 사람들, 커피샵들은 다 다르니까요.
- 이번 step은 유독 제가 처음부터 다 설계를 하는거 같은 느낌이 들었습니다. 그래서인지 let을 쓸 지 var를 쓸 지부터 엄청 고민되더라구요. 대부분 변할 수 있는 프로퍼티라고 판단해서 var를 많이 사용했습니다.
- 코드를 하나하나 쓰면서, 자꾸 제가 커피를 사는 과정을 상상했습니다. 그러지 않고선 도저히 코드로 표현하질 못하겠더라구요. 제가 주문할 상품을 고르고, 결제하고, 받는 과정까지 하나하나 나누면서 상상했습니다. 이렇게 익숙한 과정도 코드로 표현하기 쉽지 않았는데 만약 제가 잘 모르는 프로세스를 설계할 땐 얼마나 복잡해질지 😭
---
- 우선 딕셔너리들로 타입을 정해주긴 했는데, 딕셔너리에서 값을 어떻게 추출해서 사용할지는 고민해봐야할 것 같습니다. 
- 픽업 테이블은 Coffee를 담는 array타입으로 정의했기 때문에 딕셔너리에서 배열로 값을 보내주는 과정도 고민해야 될거 같습니다.
---
코드를 써가며 고민한 부분들이며 동시에 조언을 얻고싶은 부분입니다. 
- 제일 먼저 고민한 부분은 메뉴판이였습니다. enum을 통해 커피 종류까지 생각한 뒤, 가격을 묶어줘야 Person의 money와 …
> Week3 [STEP1] 애종

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/step1.swift
@horeng2
안녕하세요~ STEP 1 보내드립니다.
- 구조체와 클라스 중 어떤 타입으로 정의하면 좋을 지 생각해보았습니다. 처음에는 Person 타입을 강의 컨텐츠와 같이 Person 클라스를 만들고 하위에 내국인 / 외국인 Subclass를 나누어서 원화/달러.. 등으로 만들어볼까 하는 생각을 하다가 일단은 아직 Struct와 Class의 개념과 프로퍼티를 정확히 사용해보는 것에 초점을 맞추어 보기로 하였습니다. 
- Person과 CoffeeShop 타입은 모두 구조체로 만들었는데 현재 프로그램 구조상 상속은 필요없을 것으로 생각되어 memberwise 기능을 제공하여 초기화를 하지 않아도 되는 `Struct` 타입으로 생성하였습니다.
- 프로퍼티로 Dictionary와 enum을 사용하였는데 어떻게 호출을 해야 하는지, 설정은 어떻게 하는지 많이 헤매면서 해 본 것 같아요. 일단 작동은 하는 것 같은데.. 좀 더 많은 연습이 필요할 것 같습니다 🤔 @.@
- 아직까지 구조체와 클라스 중 어떤 타입으로 정의해야 하는지가 아리까리해요. value 타입과 reference 타입에 대한 대략적인 정의는 알고 있는데 이게 어떻게 타입을 정의하는데 사용되는 건지가 명확하지 않습니다. 혹시 참고할 만한 자료가 있을까요? Week 3 교육자료를 왔다리 갔다리 하면서 체크해보아도 어렵네요...
> Week3 [STEP 1] 메네

- CodeStarterCamp_Week3/main.swift
@yeahg-dev
- 커피숍을 머릿속으로 떠올리며 객체로 구현해보기 위해 노력했습니다🔥
---
- 이번 과제에서는 딱히 해결되지 않은 부분은 없었습니다..!
---
- 보통 객체를 만든 후에 값을 할당할때, 각각의 변수별로 다른 속성을 가질 수 있다고 생각해서 구조체를 많이 이용하게 되는데 혹시 클래스는 현업에서 어떤 경우에 사용하게 되는지 궁금합니다🧐
> WEEK3 [STEP2] 제리

- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/step1.swift
- CodeStarterCamp_Week3/step2.swift
@horeng2
안녕하세요~ STEP 2 완료하고 보내드립니다.
STEP 1에서는 커피 enum 타입의 RawValue로 한글 메뉴명을 작성했었는데 이번에는 메뉴 딕셔너리를 없애고 RawValue에 가격을 입력해 보았습니다.
Coffee enum에서는 `,`를 제거하고 `case`를 붙여 사용했습니다.
- Person 구조체를 먼저 작성한 후에 CoffeeShop 구조체를 작성하였는데 나중에 order 메소드에서 yagomBucks인스턴스의 make 메소드를 호출한다는게 살짝 헷갈렸습니다.
- 처음에 Coffee 열거형을 esspresso = 3800 이런 식으로 작성했는데 결과를 출력할 때 한글 메뉴명을 출력해야 해서 이번에는 한글 음료 이름으로 열거형을 정의했습니다.
- 해결이 되지 않은 점은 없는 것 같은데.. 뭔가 제가 알지 못하는 것을 알려주시겠죠? 🤔
- 처음 프로그램 설계시 생각한 구조를 그대로 구현하는 경우가 많은데, 그러다 보니 미처 생각하지 못한 부분들은 놓치고 넘어가는 경우가 많은 것 같아요, Swift 문법(?)이나 기능들에 대해 더 많이 알고 있다면 이런 방법, 저런 방법을 생각해 보고 어떤 방식이 이 경우에 맞을 지 고민을 해 볼텐데, 강의 컨텐츠에서 본 것이나 얼핏 아는 내용만 가지고 구현을 하다보니 놓치는 부분이 많은 것 같습니다.  
어떤 식으로 코드를 구현할지에 대한 청사진? 기획? 같은걸 잘 하려면 일단 실력을 쌓아야 겠죠? 다른 사람의 코드를 많이 보는 것도 도움이 될 것 같습니다. 호랭이가 추천해주시는 방법이 혹시 있을까요?
불금인데~ 주말 잘 보내시고 Week 4에 …
> Week3 [STEP 2] 메네

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/step1.swift
@siwonkim0 
각각의 사람을 나중에 상속받아 클래스를 만들어 줄 수 있을 것 같아서 클래스로 정의했습니다.
name, age, money, nationality, gender 를 통해 사람의 공통적인 특성을 표현했습니다.
나중에 CoffeeShop을 상속받아 브랜드 별로 특징을 추가해 줄 수 있을 것 같아서 클래스로 만들었습니다.
처음 커피숍이 생기면 매출과 pickUpTable 은 각각 0, 아무것도 없는 상태가 될 것 같아서 초기화 값에 포함시키지 않았습니다.
주문을 하면 매출과 pickUpTable 에 값이 추가되도록 설정했습니다.
> Week3 [Step 1] seoyounghan

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/step1.swift
@gogosilver 
> 
1. struct, enum타입을 사용하여 구현
> 
1. 타입을 작성할때 struct로 할까 class로 할까 고민했는데 상속이란 기능이 필요하면 class를 반대로 필요하지 않으면 struct를 사용하라는 배움을 떠올려서 아직 이구간엔 상속기능을 쓸만한 상황이 오지않은것 같아 struct 타입으로 작성했습니다.
3. 이번 스텝에서 처음으로 struct랑 enum이랑 같이 사용하는경험을 했습니다. 코드를 차근차근작성해나가면서 모르는부분은 어떻게 구현해야하는지 구글링하면서 작성했습니다.
struct타입 CoffeeShop에서 menu프로퍼티에 값을 넣어서 활용하는 상황은 아직 아닌것 같아서 스킵해두었습니다. 만약 지금 값을 넣어둬야하는상황이라면 수정하겠습니다!
> Week3 [STEP 1] LimKiWoong

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/step1.swift
- CodeStarterCamp_Week3/step2.swift
@siwonkim0 
문제 지시 사항에는 order(_ coffee: Coffee) 를 이용하라고 되어 있었는데, CoffeeShop의 인스턴스 정보를 가져와야 가격 프로퍼티와, make 메소드 호출을 할 수 있을 것 같아서 매개변수를 추가해 보았습니다. 혹시 매개변수를 추가하지 않고, 프로퍼티와 메소드를 호출할 수 있는 방법이 있는지 궁금합니다!
Step 1 에서 내용들이 추가되는 것이라 Step1 부분은 주석처리 해두었습니다!🙂
> Week3 [step 2] seoyounghan

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/step1.swift
@siwonkim0 
이번 주는 첫 번째 PR이 좀 늦었습니다.
주말 잘 보내시고 다음 주에 확인해주세요.
이번 과제에서는 Person, CoffeeShop, Coffe 타입을 만들어 보았습니다.
Coffee 타입은 커피의 한글명을 원시 값으로 하는 열거형으로 만들었습니다.
Person과 CoffeShop은 구조체와 클래스 중에 어떤 것으로 만들지 고민했습니다.
메서드에서 호출할 경우 값을 복사해서 전달하기 보다는 주소를 넘겨주는 게 더 적합하다고 생각해서 클래스로 만들었습니다.
사람이 카페에 커피를 주문할 때 구조체일 경우 카페 인스턴스를 복사하는 데, 클래스의 경우 카페 인스턴스의 참조를 전달합니다. 
Person, CoffeShop 타입 내부의 프로퍼티와 메서드는 미션 요구사항에 맞게 추가했습니다.
Person 타입에는 저장 프로퍼티 name(이름), cashInWallet(현금), 이니셜라이저(이름, 현금 초기값 할당), 메서드 orderCoffee(카페에 커피를 주문하는 메서드)를 추가했습니다.
CoffeShop 타입에는 저장 프로퍼티 name(이름), sales(매출액), menuBoard(메뉴판), pickUpTable(픽업테이블), barista(바리스타), 이니셜라이저(이름 초기값 할당), takeCoffeeOrder(커피 주문 접수하는 메서드), makeCoffee(커피 만드는 메서드), placeCoffeOnPickupTable(픽업테이블에 커피를 놓는 메서드)를 추가했습니다.
barista를 옵셔널 프로퍼티 타입으로 한 이유는 카페를 초기화한 이후에 바리스타를 할당해 주기 위해서 …
> Week3 [STEP 1] 이준호

- CodeStarterCamp_Week3/STEP1.swift
- CodeStarterCamp_Week3/main.swift
@LeeSungNo-ian `이안`님 WEEK3로 인사드립니다!! 야곰님이 말씀하시던 5주과정에서 대다수가 3주차에서 끝난다고 하던데..
저도 점점 PR드리는 속도가 늦어지고 있네요 ㅠㅠ 늦더라도 이안님이 말씀 주신 것 처럼 다 알고 넘어갈 수 있도록 노력하겠습니다🫡
주제는 객체야 놀자~인데 객체한테 폭행당한 기분이에요 ㅎ;; 부족한 거 같지만 한계를 느껴 PR 드립니다 ㅠㅠ
- 아직 상속과 같은 클래스의 추가적인 개념을 상세하게 공부하지는 않았지만 CoffeeShop은 추후 상속할 여지가 있다고 판단하여 클래스로 Person 타입은 구조체로 작성을 해보았습니다.
- 진행하며 구현하고싶던 여러 부분들이 다음 STEP의 요구사항인 것으로 파악하고 STEP1의 요구사항에만 집중해봤습니다.
---
```
func orderedMenu(coffee: Coffee) {
if let orderedCoffeePrice = menu[coffee] {
print("주문하신 \(coffee)의 가격은 \(orderedCoffeePrice)원 입니다.")
todayRevenue += orderedCoffeePrice
}
}
```
- 이 함수 부분에서 제가 `coffee` 받는 값을 enum으로 제작된 `Coffee`라는 열거형을 설정했습니다. 이런 경우 함수를 실행할 때 `Coffee` 열거형에 저장되지 않은 값을 입력하면 오류가 떴습니다! 여기까지는 당연하다고 생각을 했지만 이런 경우에 `nil` 일 경우를 미연에 방지 할 수 있는거라고 생각해야하나요!? 
- 제가 `var menu: Dictionary<Coffee, …
> Week3 [STEP1] gye0rehan

- CodeStarterCamp_Week3/main.swift
@jsim27  
나무님 안녕하세요! 즐거운 불금에 PR를 합니다😅
1. Person을 `class`로 선언한 이유
- Person(사람)이라는 타입은 지금 당장은 아니어도, 상속을 하게 될 가능성이 많을 것 같아 class로 선언하였습니다.
- 사람을 상속받아 "학생" 이나 "개발자" 조금 더 좁은 타입을 만들 수 있기 때문입니다.
2. nickName
- Person의 프로퍼티 중, nickName은 초기값이 꼭 필요하지 않을 것 같아 아래와 같이 선언하였습니다.
```
var nickName: String?
```
3. 이니셜라이저
- class는 모든 프로퍼티가 반드시 초기화되어야 합니다.
- 따라서 모든 프로퍼티를 초기화 시키는 `init(name: String, age: Int, nickName: String, money: Int)`와
- nickName의 초기화를 생략한 `init(name: String, age: Int, money: Int)`를 구현하였습니다. 
- (nickName은 후에 초기화 가능)
4. order메서드
- 열거형 Coffee 타입을 매개변수로 받는 메서드로 생각해보았습니다.
1. `struct`로 선언한 이유
- Person 타입보다 상속의 가능성이 낮다고 판단하여 struct로 선언하였습니다. 
- 또한, struct의 `memberwise` 이니셜라이즈를 사용해보고싶어서...🙄 => 후에 객체를 생성할 때 저절로 init메서드가 실행되는 것을 확인하였습니다! 싱기방기
2. takeAnOrder() 메서드와 makeCoffee() 메서드
- 두 기능으로 나눌 수 있을 …
> Week3 [STEP 1] dasankim

- CodeStarterCamp_Week3/main.swift
@July911 
- Person 타입에 이름 프로퍼티가 없어서 결과값을 출력할 때 Person(money: 1) 이런 식으로 출력되는 걸 보고 이름을 추가했습니다.
- 인스턴스의 함수가 다른 인스턴스의 함수를 호출하고 그 함수 내부에서 또 다른 함수를 호출하는 방식으로 구조가 완성되니 객체 지향이 어떤 의미인지 조금은 알게되었습니다.
- 커피 구매라는 메소드에서 구매자의 돈과 커피숍의 매출 프로퍼티에 변경을 주기 때문에 모두 mutating func를 사용했습니다.
- 주문 방식은 딕셔너리 타입을 사용하기로 했습니다. 다양한 커피와 몇 잔을 살것인지 표현하고 싶었습니다. 
- guard 를 통해 돈이 부족할 경우 코드 진행을 추가했습니다.
- 주문 받는 함수, 커피를 만드는 함수를 나눴습니다. 주문 받는 함수 파트에 추후 추가되는 기능들이 있을 수도 있고, 기능을 세분화하고싶었습니다.
---
- step 요구조건 중 커피샵 구조체 안에 메뉴판 프로퍼티를 추가하라고 했는데, enum의 연산프로퍼티를 통해 메뉴와 가격을 표현한 저는 구조체 내부에 메뉴판을 추가하지 못했습니다. 
- enum을 구조체 안에 넣자니, CoffeeShop의 모든 인스턴스가 같은 메뉴판을 가지게 되는것 같아 의미가 없다고 생각했습니다.
- 메뉴판의 구조를 가지지만 각 인스턴스는 다른 가격과 메뉴로 구성하고싶다면 어떻게 해야할까요??
```
> Week3[STEP2] 애종

- CodeStarterCamp_Week3.xcodeproj/project.pbxproj
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/step1.swift
@gogosilver 
- `enum` 을 이용해 `커피의 종류`들을 모은 열거형을 생성했습니다
- `Struct`를 이용해 `Person`과 `CoffeeShop` 타입을 생성했습니다.  값이 각각 다른 사람들과 커피숍을 생성할 수 있도록 참조타입인 `class`보다 값타입인 `struct`를 택했습니다.
- `Person 구조`에서 `name, age`는 새로운 인스턴스 생성시 정보가 없을 수 있다 생각하여 `옵셔널타입`으로 정의했고, `money`는 step1의 요구사항이라 `기본  Int`로 선언했습니다. 옵셔널타입이 있으므로 고려하여 money값으로만 이니셜화 할수있는  `init`코드를 작성했습니다.
- `Person타입`에서 `buy메소드`를 만들면서 Person 자신의 프로퍼티를 수정하기 위해서 `mutating` 키워드를 썼습니다.
- 물건을 구입하는 함수 `buy`에서 가진돈보다 가격이 넘는 물건은 사지 못하도록 `if-else구문`을 사용했고 물건 구입시 본인이 가진돈에서 구입한돈만큼 자산이 줄어들도록 작성했습니다.
- `CoffeeShop 타입`에서 인스턴스 생성이 새로 오픈한 카페라고 생각하여 `sales(판매액) 을 0을 기본값`으로 넣어줬습니다. 커피숍마다 barista의 정보와 메뉴판  `이니셜한 후에 추가/변경` 해주기 위해서 `옵셔널타입`으로 정의했습니다. 더불어 `메뉴판의 Key`는 타입을 `열거형 Coffee`로 한정했습니다.
- `주문을 받는 함수(takeOrder)`는 메뉴판의 타입과 맞춰 `열거형 Coffee`로 한정했습니다. 주문을 받으면 `make함수`를 돌리고 …
> Week3 [Step1] sunny

- CodeStarterCamp_Week3/main.swift
@eunseo5355 
3주차 과제도 힘내서 해볼게요!
- 과제에서 요구하는 프로퍼티와 메소드말고도 사람과 커피숍의 프로퍼티나 메소드가 될 수 있을만한 부분들에 대해 고민해봤습니다. name의 경우 인스턴스가 생성되면서 자체적인 이름이 부여되지만 바리스타가 누군지 print 함수로 출력해 보이는 등의 경우를 위해 생성한 프로퍼티입니다.
- 전역변수를 선언하지 않고서는 인스턴스 생성시 이니셜라이저에 값으로 넣기 번거로운 menu나 pickUpTable은 초기값을 부여했습니다.
---
- 저는 이니셜라이저를 통해 CoffeeShop 클래스의 인스턴스 생성시 바리스타를 입력받는 것으로 설정하였는데, 과제에서는 인스턴스 생성과 바리스타 할당을 구분해서 사용하기 때문에 missKim으로 생성한 뒤 misterLee로 변경하였습니다. 
- misterLee가 할당되기 전에 다른 값을 할당하고 싶지 않은데, Person 타입의 빈 값이 없기 때문에 초기값으로 빈값을 줄 수도 없었습니다. 그렇다고 프로퍼티를 정의하면서 var barista: Person?으로 적용하자니 나중에 바리스타 관련해서 사용할 때 옵셔널 취급을 받는 점이 걸려서요.
- struct로 정의해서 memberwise의 도움을 받아볼까 생각하기도 했는데 그러려면 이니셜라이저를 통으로 없애야 하기 때문에, name이나 grossSales 등도 따로따로 할당해야하는 점이 불편했습니다.
- 이럴 때 좋은 해결 방법이 있을까요? 사실 name이나 grossSales를 따로 할당하면 안되는 이유는 없으니까 memberwise를 통한 해결방법이 제일 현실적인 것 …
> Week3 [STEP 1] Gundy

- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/step1.swift
@gogosilver 
> step1에서 사용했던 struct타입인 CoffeeShop은 참조하는기능이 필요하여 값복사인 struct타입이 아닌값을 참조하는 class타입을 기용했습니다. 
기존에 추가하지못했던 메뉴값에 값을 넣어주고
커피를 주문하면 주문자가 가진돈에서 커피값을 차감하고
가게매출은 커피값을 더했습니다.
> Person타입의 purchaseCoffee메서드 파라미터인 coffeeShop의 메서드 makeCoffee를 호출하려할때 
struct타입의 특징 중 하나인 값을복사하는 특징때문에 이러한 오류가 나는것을 확인했습니다. 
> 이러한식으로 고칠수도있을텐데 이는 근복적으로 값을 참조하는것이 아닌 그저 복사하는것이기 때문에 가게매출에 아무리 더하고빼봤자 원본에는 영향이 가질 않습니다. 
때문에  CoffeShop struct에서class로 구현하는방향으로 진행했습니다.
> Week3 [STEP2] LimKiWoong

- CodeStarterCamp_Week3/WEEK3 STEP1.swift
- CodeStarterCamp_Week3/main.swift
@gogosilver 안녕하세요 선생님 WEEK3 STEP1 진행했습니다 확인 부탁드립니다!
타입을 만들 때 Class와 Struct 중 어떤 것을 사용해야하는지 고민을 했습니다.
어떤 것을 사용해야할 지 결정하기 위해서 둘의 차이점을 생각해봤습니다.
Class의 경우 참조타입이고 Struct의 경우에는 값타입입니다.
참조타입의 경우 사이트 링크와 같은 개념으로 참조대상의 값이 변경되면 변경된 값이 반영된다.
또한 참조타입은 상속이 가능하다.
`misterLe` 와 `missKim` 은 오직 본인들만 존재하고 상속 같은 기능을 사용하지 않을것으로 생각이 들어 값타입인 Struct를
사용하기로 결정했습니다.
참조타입인 Class의 경우에는 상속이 필요할 때 외에는 어떤 상황일 때 사용해야할지 아직 감이 안 잡힙니다 ㅜㅜ
> WEEK3 [STEP1] 남준

- CodeStarterCamp_Week3/main.swift
@eunseo5355
헤일리! 지난번 merge 코멘트도 잘 읽었습니다!
해당 사항 반영하면서 STEP 2 진행했어요 😃
- STEP 2 내용을 보지 않고 STEP 1을 진행했었는데, 상당수의 메소드가 이미 STEP 1에서 구현되어있어서, 세부적인 내용만 조금 다듬었습니다. 과제 상에서는 Person의 메소드인 order를 사용하면 바로 CoffeeShop의 메소드인 make를 호출하라고 했는데, 저는 takeOrder 메소드를 만들어 둔 게 있어서 주문, 제조, 제공의 순서로 호출이 맞물리게 코드를 작성해보았습니다.
- order 메소드를 사용할 때, 잔액이 부족할경우 takeOrder를 호출하지 않게 조건문을 작성하였습니다.
- grossSales의 초기값은 0원으로 설정하였습니다. 손님을 맞이하기 전에는 매출이 0원인 것이 자연스럽다고 생각했습니다.
---
- 제가 요즘 진도에 따른 학습과 복습을 병행하는데요, 미션에 있는 코드들도 다 복습하고 있습니다. 일주일 남짓밖에 차이나지 않는데도 코드의 효율성은 차이가 크더라고요. 결국 지금 작성한 코드들도 다음주나 다다음주의 저는 더 효율적으로 할 수 있으리란 믿음을 갖고 열심히 하고 있습니다.
- 효율과는 다른 이야긴데, 같은 결과를 내는 코드는 많잖아요? 혹시 복습할 때, 기존과는 다른 방법으로 코드를 작성해보는 게 좋을까요? 현재는 처음부터 코드를 작성하기는 하지만, 결과적으로 큰 틀에서는 비슷하고 기존 작성방식에서 줄일 수 있는 부분을 짧게 줄여나가는 방향으로 복습하고 있습니다.
- 의식적으로 다양한 방법으로 연습해보는 것이 좋을까요?
---
헤일리 …
> Week3 [STEP 2] Gundy

- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/step1.swift
@siwonkim0 
Step 1 을 하면서 Step 2에서 해야할 부분을 대부분 해버렸네요.
makeCoffee 메서드에 name 전달 인자를 추가하고 출력 문구를 수정했습니다.
> Week3 [STEP 2] 이준호

- CodeStarterCamp_Week3/main.swift
@jsim27 
나무님 안녕하세요! 셋째주 두번째 미션 PR입니다:)
class와 struct의 참조 타입과 값 타입에 대해서 이해했다고 생각했는데,
실제 코딩 제 마음과 다르게 움직이는 것을 보고 엄청 헤매다가 클래스와 구조체에 대해 하나 더 배웠습니다.
- order() 메서드를 실행하여
- yagomBucks의 make() 메서드를 호출
인데, `order 메서드`를 실행하면 자동적으로 `make 메서드`를 호출하게 만들라는 뜻인가...?
라고 해석하였습니다. 그래서
- Person 안에 CoffeeShop 타입의 `favoriteCoffeeShop` 프로퍼티를 선언하여
- Person의 order메소드 안에서 `favoriteCoffeeShop.make` 메소드를 호출하도록 하였습니다.
지난 스텝 때, `CoffeeShop` 타입을 구조체로 구현하였었습니다.
구조체로 구현했던 이유는 상속이 필요하지 않다고 판단했기 때문이었는데요,
그 상태로 step2를 진행하다보니 아래와 같은 난관에 부딪혔습니다.
```swift
struct CoffeeShop {
var sales: Int = 0
var menu: [Coffee: Int] = [.americano: 2000, .cappuccino: 2500, .espresso: 1500, .flatWhite: 3000, .latte: 2500, .macchiato: 3000, .mocha: 2500 ]
var pickUpTable: [Coffee] = []
var barista: Person?
mutating func make(_ coffee: Coffee, …
```
> Week3 [STEP2] dasanKim

- CodeStarterCamp_Week3/main.swift
@July911 week3 step1 드디어 완료했습니다. 
사실 미션을 푸는 데 있어서는 큰 어려움이 없었습니다. 아직 상속에 대해서는 배우지 않았고 initializer를 설정해주어야하는 class에 비해 memberwise 기능이 있는 struct를 쓰는 것이 훨씬 나을 것 같다는 생각이 들었습니다. 
주문받고 커피를 만드는 것은 한번에 하는 것이 나을 것 같아 함수명이 길지만 길게 지어보았습니다. Coffeeshop이라는 struct안에 pickUPTable이라는 array를 만들고 그 안에 내용을 추가하는 것이기에 구조체 안의 프로퍼티를 변경하는 함수여서 mutating을 써야한다는 것을 끝에서야 깨달아 쓴 것이 가장 큰 배움이었습니다.
제가 고민이 되는 것이 Person이라는 struct와 Coffeeshop이라는 struct를 연결하는 부분입니다. 주문자가 커피를 주문했으면 그 주문내역을 Coffeeshop에서 전달받아야 자연스러운 코드가 나올 것 같은데 배웠던 내용인지 아닌지가 헷갈려서 만약 배운 것이 아니라면 어떻게 둘을 자연스럽게 연결할 수 있을지에 대해 조언 부탁드립니다!
> [Week3] Step1 상수동남자

- CodeStarterCamp_Week3/STEP1.swift
- CodeStarterCamp_Week3/STEP2.swift
- CodeStarterCamp_Week3/STEP3.swift
- CodeStarterCamp_Week3/main.swift
@LeeSungNo-ian 안녕하세요 `이안`님!
Week3 STEP2 작성해봤습니다. 객체는 서로 소통한다라는 주제를 조금은 이해해볼수 있는 과정이 된 거 같습니다!!
- 요구사항에 맞게 결과는 출력이 되지만, 여러 인스턴스들이 `optinal`일 여지가 있다고는 생각이 많이 들었습니다.
모든게 있을 수도 있고, 없을 수도 있는거라 생각이 들었습니다... 
- americano 를 한글로 아메리카노로 출력하기 위해 , `rawValue`를 이용해봤습니다. 이 방법을 찾기 위하여 열거형을 구글링을 해보았는데 `switch`를 활용해서도 가능할거 같다고 생각이 들었습니다. 어떤 방법이 더욱 좋은 방법인지도 궁금합니다!
> Week3 [STEP2] gye0rehan

- CodeStarterCamp_Week3/coffeeShop.swift
- CodeStarterCamp_Week3/main.swift
- CodeStarterCamp_Week3/person.swift
@jaemuYeo 잼킹! Setp2 PR이에욥!!
- 좀 더 코드를 간결하게 최적화하려고 했지만 지금 상태가 좋은 거 같았습니다.
- order 메서드에서 부족한 잔액을 계산할 때 어떤 커피를 선택했는지에 따라 가격이 달라지기 때문에 옵셔널 바인딩을 사용해 주었습니다.
> [Round3] Setp2 - joo
